services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.back
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - LLM_PROVIDER=gemini
    secrets:
      - open_api_key
      - gemini_api_key
    networks:
      - app-network

  frontend:
    image: antonbiz/agent-front:1.0
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

secrets:
  open_api_key:
    file: ./secrets/open_api_key.txt
  gemini_api_key:
    file: ./secrets/gemini_api_key.txt