name: Lint Python Backend

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'back/**/*.py'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'back/**/*.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort mypy
        cd back && pip install -r requirements.txt
    
    - name: Run Black (code formatting check)
      run: |
        cd back && black --check --diff .
    
    - name: Run isort (import sorting check)
      run: |
        cd back && isort --check-only --diff .
    
    - name: Run mypy (type checking)
      run: |
        cd back && mypy . --ignore-missing-imports